INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE dwf_analog_discovery_2_community_module)

FIND_PATH(
    DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_INCLUDE_DIRS
    NAMES dwf_analog_discovery_2_community_module/api.h
    HINTS $ENV{DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_DIR}/include
        ${PC_DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_LIBRARIES
    NAMES gnuradio-dwf_analog_discovery_2_community_module
    HINTS $ENV{DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_DIR}/lib
        ${PC_DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE DEFAULT_MSG DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_LIBRARIES DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_INCLUDE_DIRS)
MARK_AS_ADVANCED(DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_LIBRARIES DWF_ANALOG_DISCOVERY_2_COMMUNITY_MODULE_INCLUDE_DIRS)

